services:
  bot:
    image: ghcr.io/profiidev/images/rust-musl-watch:main
    volumes:
      - ./bot:/app
    tty: true
    entrypoint: ['tini', '--']
    command: ['cargo', 'watch', '-x', 'run']
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - '9301:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'test']
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 1s